### ISSUE TITLE
Errors in blend OS 4 alpha

### ISSUE THREAD

**Issue by lavilao** [blend-os/akshara#2]
Hi, I am trying to use blend OS 4 with the gnome track but it's not working. I AM stuck at sudo mkinitcpio -P; sudo akshara update. After downloading and installing all packages it gives error saying that return_val can't be none type (might be because I don't have any aur package?) And also it throws error about command(), the one below with system_lock:.

**Comment by lavilao** [comment]
here is the log
[akshara.log](https://github.com/blend-os/akshara/files/13802246/akshara.log)
it also gives error with the linuxloops hook, my guess is that it does not found it when is chrooted. is there a way to copy my hooks to the chroot enviroment when doing akshara update?

**Comment by lavilao** [comment]
Upon reboot the system is not updated, it's read only however My guess is that is due to conflict with linuxloops (the Hook not running in chroot) as it's the one that manages the grub configs.

**Comment by lavilao** [comment]
managed to fix the error of linuxloop hook by adding 
```
exec('mkdir', '-p', '/.new_rootfs/usr/lib')
        exec('cp', '-r', '/usr/lib/linuxloops', '/.new_rootfs/usr/lib')
        exec('mkdir', '-p', '/.new_rootfs/etc/initcpio/install')
        exec('cp', '/etc/initcpio/install/linuxloops', '/.new_rootfs/etc/initcpio/install')
```
to the script but the error still persists
```
Traceback (most recent call last):
  File "/home/luis/./akshara", line 435, in <module>
    command()
  File "/home/luis/./akshara", line 302, in update_system
    return_val = exec_chroot(
                 ^^^^^^^^^^^^
TypeError: Value after * must be an iterable, not NoneType
```

**Comment by MiMillieuh** [comment]
> managed to fix the error of linuxloop hook by adding
> 
> ```
> exec('mkdir', '-p', '/.new_rootfs/usr/lib')
>         exec('cp', '-r', '/usr/lib/linuxloops', '/.new_rootfs/usr/lib')
>         exec('mkdir', '-p', '/.new_rootfs/etc/initcpio/install')
>         exec('cp', '/etc/initcpio/install/linuxloops', '/.new_rootfs/etc/initcpio/install')
> ```
> 
> to the script but the error still persists
> 
> ```
> Traceback (most recent call last):
>   File "/home/luis/./akshara", line 435, in <module>
>     command()
>   File "/home/luis/./akshara", line 302, in update_system
>     return_val = exec_chroot(
>                  ^^^^^^^^^^^^
> TypeError: Value after * must be an iterable, not NoneType
> ```

Got the same issue

**Comment by lavilao** [comment]
> > managed to fix the error of linuxloop hook by adding
> > 
> > ```
> > exec('mkdir', '-p', '/.new_rootfs/usr/lib')
> >         exec('cp', '-r', '/usr/lib/linuxloops', '/.new_rootfs/usr/lib')
> >         exec('mkdir', '-p', '/.new_rootfs/etc/initcpio/install')
> >         exec('cp', '/etc/initcpio/install/linuxloops', '/.new_rootfs/etc/initcpio/install')
> > ```
> > 
> > to the script but the error still persists
> > 
> > ```
> > Traceback (most recent call last):
> >   File "/home/luis/./akshara", line 435, in <module>
> >     command()
> >   File "/home/luis/./akshara", line 302, in update_system
> >     return_val = exec_chroot(
> >                  ^^^^^^^^^^^^
> > TypeError: Value after * must be an iterable, not NoneType
> > ```
> 
> Got the same issue
its because of no aur-packages. If You define one the error Will not appear, the problem is found an aur package that can be installed that early, I tried adding hello from aur to test and it could not be compiled, Will try now with yay-bin to SEE.

**Comment by lavilao** [comment]
Yep, adding a aur-packages fixed the problem and the system booted to an updated versión. Am worried now about this error messages on boot thou:
Can't rename './dkms' no such file or directory.
The same happens with ./passim and with ./packagekit

**Comment by Ast3risk-ops** [comment]
Please keep in mind the source for this is actually being developed at https://git.blendos.co/blendOS/system-tools/akshara, this repo is severely out of date.

**Comment by Ast3risk-ops** [comment]
> Will try now with yay-bin to SEE.

the `aur_packages` option is powered by [`paru`](https://github.com/Morganamilo/paru), which we compile to [our repo](https://pkg-repo.blendos.co).

**Comment by lavilao** [comment]
> Please keep in mind the source for this is actually being developed at https://git.blendos.co/blendOS/system-tools/akshara (signups have to be approved by Rudra), this repo is severely out of date.

thanks for the info!

> the aur_packages option is powered by [paru](https://github.com/Morganamilo/paru), which we compile to [our repo](https://pkg-repo.blendos.co/).

yes I knew that, what I ment was to add the yay-bin as a aur package to test as I tried adding the hello aur package and it throws errors so I needed a package that I knew it would work so TLDR: I used yay because it was the only aur package I was sure t would work

**Comment by Ast3risk-ops** [comment]
@lavilao we're planning to move most of our repos over and mirror them to github.
